# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  AJ:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  G0:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  G1:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  XJ:
    has_velocity_limits: true
    max_velocity: 0.03
    has_acceleration_limits: false
    max_acceleration: 0
  YJ:
    has_velocity_limits: true
    max_velocity: 0.03
    has_acceleration_limits: false
    max_acceleration: 0
  ZJ:
    has_velocity_limits: true
    max_velocity: 0.03
    has_acceleration_limits: false
    max_acceleration: 0
